# Numpy Exercise Solution  <img src = "numpy1.png">
###### Authored by T.K.Senthil Kumar

#### 1. Create a numpy array with the number of elements equals your age. The value of array elements is a random number between 10 to your age 

In [22]:
#Solution
import numpy as np

sol1=np.random.randint(10,35,size=(1,34))
sol1=np.squeeze(sol1)
print(sol1)
print(sol1.shape)

[18 11 13 32 23 20 17 33 26 12 31 34 34 29 31 10 31 20 32 10 13 34 10 18
 29 11 30 22 13 31 10 10 10 17]
(34,)


#### 2. Create a numpy array between 1 to 50 with the span(space) of 2 and print the length of the array

In [8]:
# Solution
sol2=np.arange(1,50,2)
print(len(sol2))


25


#### 3. Create an equally spaced numpy array with 27 elements between 4 and 7 

In [10]:
# Solution
sol3=np.linspace(4,7,27)
print(sol3)

[4.         4.11538462 4.23076923 4.34615385 4.46153846 4.57692308
 4.69230769 4.80769231 4.92307692 5.03846154 5.15384615 5.26923077
 5.38461538 5.5        5.61538462 5.73076923 5.84615385 5.96153846
 6.07692308 6.19230769 6.30769231 6.42307692 6.53846154 6.65384615
 6.76923077 6.88461538 7.        ]


#### 4. Create a matrix of size (5 x 4) with random numbers and round off the each elements by only 2 fractional points.

In [13]:
# Solution
sol4=np.random.rand(5,4)
sol4=np.round(sol4,2)
print(sol4)


[[0.41 0.76 0.99 0.85]
 [0.89 0.52 0.61 0.36]
 [0.4  0.99 0.91 0.34]
 [0.47 0.24 0.96 0.9 ]
 [0.54 0.03 0.57 0.79]]


#### 5. Create a matrix of size (5x5) with random integers between 5 to 15

In [14]:
# Solution
sol5=np.random.randint(5,16,size=(5,5))
print(sol5)


[[15 12 11 11  9]
 [12 14 13  7  6]
 [12  6 12 11  6]
 [ 5 12 11 12  8]
 [ 5  8 10  7 12]]


#### 6. Create the one dimensional array of zeros of random length below 20 with the data type int32

In [21]:
# Solution
sol6=np.zeros([1,np.random.randint(20)],dtype='int32')
print(sol6)


[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]


#### 7. Create a two dimensional array of ones of random row and column lengths with the data type of float32 

In [27]:
# Solution
sol7=np.ones([np.random.randint(20),np.random.randint(20)],dtype='int32')
print(sol7)


[[1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1]]


#### 8. Create a matrix exactly as same as shown below and print its shape, type and dtype
<img src = "np_mat1.png">

In [30]:
# Solution
mat=np.array([[9,25,50,34,45],[3,34,34,65,2],[5,7,3,76,3],[7,8,6,54,6],[23,12,8,5,8]])
print(mat.shape)
print(type(mat))
print(mat.dtype)

(5, 5)
<class 'numpy.ndarray'>
int32


#### 9. Access the center pixel of the matrix defined in the question no 8 ( Don't enter the row and column index explicitely)

In [32]:
# Solution
print(mat[2,2])


3


#### 10. Print the all the elements of 3rd row of the matrix

In [37]:
# Solution
print(mat[2,:])

[ 5  7  3 76  3]


#### 11. Print the all the elements of 4th columns of the matrix

In [40]:
# Solution
print(mat[:,3])

[34 65 76 54  5]


#### 12. Print the 4 corner pixels of the matrix

In [43]:
# Solution
c1=mat[[0,4],:]
c2=c1[:,[0,4]]
print(c2)

[[ 9 45]
 [23  8]]


#### 13. Create three matrix m1,m2,m3 with the elements grouped in the figure below
<img src = "np_mat2.png">

In [49]:
# Solution 
m1=mat[0:2,2:4]
print('The first matrix m1 :\n', m1)
m2=mat[3:5,0:2]
print('The second matrix m2 :\n',m2)
m3=mat[2:5,2:5]
print('The third matrix m3 :\n',m3)

The first matrix m1 :
 [[50 34]
 [34 65]]
The second matrix m2 :
 [[ 7  8]
 [23 12]]
The third matrix m3 :
 [[ 3 76  3]
 [ 6 54  6]
 [ 8  5  8]]


#### 14. Reshape all the three matrix segmented in the above task in to three  1-dimensional vector.

In [56]:
# Solution
m11=m1.reshape([1,-1])
print(m11)
m21=m2.reshape([1,np.size(m2)])
print(m21)
m31=m3.reshape([1,-1])
print(m31)

[[50 34 34 65]]
[[ 7  8 23 12]]
[[ 3 76  3  6 54  6  8  5  8]]


#### 15. Concatenate the matrix m1 and m2 in both vertical and horizontal direction

In [59]:
# Solution
mh=np.hstack([m1,m2])
print("The horizontal stack matrix : \n",mh)
mv=np.vstack([m1,m2])
print("The vertical stack matrix : \n",mv)

The horizontal stack matrix : 
 [[50 34  7  8]
 [34 65 23 12]]
The vertical stack matrix : 
 [[50 34]
 [34 65]
 [ 7  8]
 [23 12]]


#### 16. Add, Subtract, multiply, divide the matrixes m1 and m2

In [60]:
# Solution
m_add=m1+m2
print('Addition result \n',m_add)
m_sub=m1-m2
print('Subtraction result \n',m_sub)
m_mul=m1*m2
print('Multiplication result \n',m_mul)
m_div=m1/m2
print('Division result \n',m_div)

Addition result 
 [[57 42]
 [57 77]]
Subtraction result 
 [[43 26]
 [11 53]]
Multiplication result 
 [[350 272]
 [782 780]]
Division result 
 [[7.14285714 4.25      ]
 [1.47826087 5.41666667]]


#### 17. Add the m1 with m3 by removing the first row and last column of m3

In [63]:
# Solution
m3_new=m3[1:,:-1]
print(m3_new)
print(m1+m3_new)


[[ 6 54]
 [ 8  5]]
[[56 88]
 [42 70]]


#### 18. Form the matrix m4 by concatenating (as a new row) the vector [me1, me2] with the matrix m1, where me1 and me2 are the mean values of each column on m1.

In [69]:
# Solution
me1=np.mean(m1[:,0])
me2=np.mean(m1[:,1])
print(me1,me2)
me1=np.hstack([me1,me2])
print(me1)
me=np.mean(m1,axis=0)# by using axis = 0 ,we can compute mean of each column, axis=1 will compute for each row
print(me) 

m4=np.vstack([m1,me])
print(m4)

42.0 49.5
[42.  49.5]
[42.  49.5]
[[50.  34. ]
 [34.  65. ]
 [42.  49.5]]


#### 19. Perform the matrix multiplication between m3 and m4

In [73]:
# Solution
print(m4.shape)
print(m3.shape)
mat_mul=np.dot(m3,m4)
print(mat_mul)

(3, 2)
(3, 3)
[[2860.  5190.5]
 [2388.  4011. ]
 [ 906.   993. ]]


#### 20. Compute the maximum and minimum value of mean, variance, standard deviation for each row of matrix created in question number 8.

In [84]:
# Solution
mat_me=np.mean(mat,axis=1)
mat_var=np.var(mat,axis=1)
mat_std=np.std(mat,axis=1)
print(np.round((mat_me),2))
print(np.round((mat_var),2))
print(np.round((mat_std),2))

[32.6 27.6 18.8 16.2 11.2]
[214.64 548.24 820.16 357.76  39.76]
[14.65 23.41 28.64 18.91  6.31]


#### 21. Compute the average and strike rate for each player and sort it decending way (seperately for avg and strike rate)
<img src = 'crick1.png'>

In [224]:
# Solution 
score=np.array([['MSD',54,60,10,65],['Kholi',102,2,78,32],['Rohit',3,110,1,92],
                ['Rahul',56,6,12,42],['Dhawan',12,8,22,11]])
print(score)
run=score[:,1:5]
print("\n The run matrix \n",run)
run1=run.astype('int32')  # to make the run as integer
print('\n The run matrix in integer \n',run1)

avg=run1.mean(axis=1)
print("\n The average score for each player \n",avg)

avg1=avg.reshape([5,1])
score_avg=np.concatenate([score,avg1],axis=1) # concatenating the average value as last column
print('\n Players score with Average \n',score_avg)

ind=avg.argsort() # to get the index based on sort (ascending)
final_list=score_avg[ind,:][::-1] #::1 is the operator which sort in a desending way
print('\n Final player oder list based on their average \n',final_list)

[['MSD' '54' '60' '10' '65']
 ['Kholi' '102' '2' '78' '32']
 ['Rohit' '3' '110' '1' '92']
 ['Rahul' '56' '6' '12' '42']
 ['Dhawan' '12' '8' '22' '11']]

 The run matrix 
 [['54' '60' '10' '65']
 ['102' '2' '78' '32']
 ['3' '110' '1' '92']
 ['56' '6' '12' '42']
 ['12' '8' '22' '11']]

 The run matrix in integer 
 [[ 54  60  10  65]
 [102   2  78  32]
 [  3 110   1  92]
 [ 56   6  12  42]
 [ 12   8  22  11]]

 The average score for each player 
 [47.25 53.5  51.5  29.   13.25]

 Players score with Average 
 [['MSD' '54' '60' '10' '65' '47.25']
 ['Kholi' '102' '2' '78' '32' '53.5']
 ['Rohit' '3' '110' '1' '92' '51.5']
 ['Rahul' '56' '6' '12' '42' '29.0']
 ['Dhawan' '12' '8' '22' '11' '13.25']]

 Final player oder list based on their average 
 [['Kholi' '102' '2' '78' '32' '53.5']
 ['Rohit' '3' '110' '1' '92' '51.5']
 ['MSD' '54' '60' '10' '65' '47.25']
 ['Rahul' '56' '6' '12' '42' '29.0']
 ['Dhawan' '12' '8' '22' '11' '13.25']]


In [225]:
# Solution 
balls=np.array([['MSD',50,42,22,78],['Kholi',95,8,65,43],['Rohit',9,100,7,101],
                ['Rahul',27,3,11,31],['Dhawan',24,20,36,27]])
print(balls)
ball=balls[:,1:5]
print("\n The ball matrix \n",ball)
ball1=ball.astype('int32')  # to make the run as integer
print('\n The ball matrix in integer \n',ball1)

strike_rate=run1/ball1 *100
sr=strike_rate.mean(axis=1)
print("\n The strike rate for each player \n",sr)

sr1=sr.reshape([5,1])
player_sr=np.concatenate([balls,sr1],axis=1) # concatenating the strike rate value as last column
print('\n Players ball faced with strike rate \n',player_sr)

ind=sr.argsort() # to get the index based on sort (ascending)

final_list_sr=player_sr[ind,:][::-1]
print('\n Final player oder list based on their strike rate \n',final_list_sr)


[['MSD' '50' '42' '22' '78']
 ['Kholi' '95' '8' '65' '43']
 ['Rohit' '9' '100' '7' '101']
 ['Rahul' '27' '3' '11' '31']
 ['Dhawan' '24' '20' '36' '27']]

 The ball matrix 
 [['50' '42' '22' '78']
 ['95' '8' '65' '43']
 ['9' '100' '7' '101']
 ['27' '3' '11' '31']
 ['24' '20' '36' '27']]

 The ball matrix in integer 
 [[ 50  42  22  78]
 [ 95   8  65  43]
 [  9 100   7 101]
 [ 27   3  11  31]
 [ 24  20  36  27]]

 The strike rate for each player 
 [ 94.91125541  81.69675643  62.17703913 162.99554687  47.96296296]

 Players ball faced with strike rate 
 [['MSD' '50' '42' '22' '78' '94.91125541125541']
 ['Kholi' '95' '8' '65' '43' '81.69675642594859']
 ['Rohit' '9' '100' '7' '101' '62.17703913248468']
 ['Rahul' '27' '3' '11' '31' '162.99554686651462']
 ['Dhawan' '24' '20' '36' '27' '47.96296296296296']]

 Final player oder list based on their strike rate 
 [['Rahul' '27' '3' '11' '31' '162.99554686651462']
 ['MSD' '50' '42' '22' '78' '94.91125541125541']
 ['Kholi' '95' '8' '65' '43' '81.69

#### 22. The students mark was recorded in a numpy array: marks = np.array([65,84,47,56,89,98,48,77,80,39]).  Cutoff for pass is 50 marks. Write the logic to print the number of students passed and failed. 

In [265]:
# Solution
marks = np.array([65,84,47,56,89,98,48,77,80,39])
pass_ind=np.where(marks>=50)
pass_marks=marks[pass_ind]

fail_ind=np.where(marks<50)
fail_marks=marks[fail_ind]

print('The Number of Students passed = ',len(pass_marks))
print('The Number of Students failed = ',len(fail_marks))

The Number of Students passed =  7
The Number of Students failed =  3


#### 23. The class incharge decided to give a mercy mark of 5 for those who scored between 45 and 49. Also the bonus of 5 marks awarded to the students who scored more than 80. Print all the student marks and compute the increase in the pass percentage of class. Any score more than 100 must be recorded as only 100.

In [266]:
# Solution
boost_mark=marks.copy()
mercy_ind=np.where((boost_mark>=45) & (boost_mark<=49))
boost_mark[mercy_ind]=boost_mark[mercy_ind]+5

bonus_ind=np.where((boost_mark>80) & (boost_mark<=95))
boost_mark[bonus_ind]=boost_mark[bonus_ind]+5

bonus_ind1=np.where(boost_mark>95)
boost_mark[bonus_ind1]=100

print('Actual Students marks \n',marks)
print('Boosted Students marks \n',boost_mark)

actual_pass_percent=(len(marks[np.where(marks>=50)])/len(marks))*100 
boosted_pass_percent=(len(boost_mark[np.where(boost_mark>=50)])/len(boost_mark))*100 
inc_pass_percent=boosted_pass_percent-actual_pass_percent
print('The increase in pass percentage is : ',inc_pass_percent)

Actual Students marks 
 [65 84 47 56 89 98 48 77 80 39]
Boosted Students marks 
 [ 65  89  52  56  94 100  53  77  80  39]
The increase in pass percentage is :  20.0


#### 24. Print the time taken for performing the following operation using list and numpy array
####       (x(i)^2 +8) / y(i),   where x and y are real integers from 1 to 60000

In [286]:
# Solution
import time
x=range(1,60000)
y=range(1,60000)
out=[]

st=time.time()
for i,j in zip(x,y):
    out.append((x[i-1]*x[i-1]+8)/y[i-1])

print('Time taken to complete the computation using LIST is : ', (time.time()-st)*1000)

x_ar=np.arange(1,60000)
y_ar=np.arange(1,60000)
st_ar=time.time()
out_ar=((x_ar*x_ar)+8)/y_ar
print('Time taken to complete the computation using NUMPY ARRAY is : ', (time.time()-st_ar)*1000)

Time taken to complete the computation using LIST is :  99.27868843078613
Time taken to complete the computation using NUMPY ARRAY is :  11.988639831542969


#### 25. Create a Github account and upload your solution with the short write-up on Numpy

In [ ]:
# Solution

https://github.com/tkseneee

